# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('has_verified_phone_no', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
