# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_verified_phone_no',
            new_name='verified_phone_no',
        ),
    ]
