# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0004_sessiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontoken',
            name='last_request_on',
            field=models.DateField(auto_now=True),
        ),
    ]
