# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0008_usermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
    ]
